export const recipes = [
  {
    id: 1,
    name: 'Puy lentils, squash & kale',
    imageOne: "/images/recipe1.jpg",
    prep: '15 mins',
    cook: '35 mins',
    difficulty: 'Easy',
    serves: '4',
    blurb: 'This hearty salad is iron-rich and full of autumn flavours - serve on its own or as a Sunday roast side dish',
    ingredients: ['1 bay leaf', '200g puy lentils', '2 tbsp olive oil', '1 ½ lemons', '20g butter', '2 large sage leaves', '500g butternut squash or another autumn squash', '100g kale',  '1 tbsp roughly chopped flat-leaf parsley', '2 tbsp toasted hazelnuts' ],
    method: ['Bring a pan of salted water to the boil. Add the bay leaf and lentils, and cook for 12-15 mins until the lentils are tender but still have some bite. Drain, put in a bowl with 1 tbsp olive oil and the lemon juice, then combine.', 'Melt the butter in a heavy bottomed frying pan or skillet that has a lid, along with the sage and remaining oil. Add the squash and some seasoning, then stir to coat them in the butter. Put the lid on and cook over a medium heat for 8-10 mins or until just tender, adding a splash of water if you need to stop it catching.', 'Add another splash of water to the pan along with the kale. Put the lid on to steam for 3-4 mins until the kale is tender. Put the lentils on a serving platter and arrange the squash and kale on top. Garnish with the parsley and hazelnuts and squeeze over 1 tbsp lemon juice from the remaining lemon wedges, to serve.']
  },
  {
    id: 2,
    name: 'Slow-cooked pork, cider & sage hotpot',
    imageOne: "/images/recipe2.jpg",
    prep: '40 mins',
    cook: '3 hours',
    difficulty: 'Medium',
    serves: '6',
    blurb: 'Warm up as the cold nights set in with this glorious hotpot, with slow-cooked pork cooked in cider and sage. It\'s topped with a crispy layer of potatoes',
    ingredients: ['4 tbsp olive oil', '1kg diced pork shoulder', '20g butter', '4 leeks', '4 garlic cloves', '3 tbsp plain flour', '500ml dry cider', '400ml chicken stock',  '2 bay leaves', '½ small bunch parsley', 'small bunch sage', '200ml single cream', '400g Maris Piper or King Edward potatoes', '400g sweet potatoes' ],
    method: ['Heat half of the oil in a deep ovenproof frying pan, or flameproof casserole dish, and fry the pork pieces over a medium high heat in batches until seared all over, then transfer to a plate. Add another 1 tbsp oil to the pan, if you need to, while you’re cooking the batches. Once all the pork is seared, transfer to a plate and set aside.', 'Add another 1 tbsp oil to the pan with a little butter and fry half the leeks with a pinch of salt for 10 mins until tender. Add the garlic, fry for a minute, then stir in the flour.', 'Pour in the cider, a little at a time, stirring to pick up any bits stuck to the bottom of the pan and to combine everything. Add the stock, bay leaves and seared pork, then simmer, half-covered with a lid for 1-1½ hrs until the meat is just tender (it will later cook to the point of falling apart in the oven). Can be prepared a day ahead.', 'Heat the oven to 200C/180C fan/gas 6. Simmer uncovered for a few minutes to reduce the sauce, if you need to – it shouldn’t be too liquid or the potatoes will sink into the sauce. Stir in the parsley, chopped sage, remaining leeks, and the cream, then season well.', 'Peel both types of potatoes and cut into slices 2mm thick, by hand or using a mandoline. Alternate layers of potato and sweet potato in circles over the pie, or randomly, if you prefer. Dot the cubed butter over the top and bake for 1-1½ hrs until the potato is tender. Nestle in the whole sage leaves, brushed in a little oil, for the last 10 mins. Leave to rest for 10 mins before serving.']
  },
  {
    id: 3,
    name: 'Caramel pear blondies',
    imageOne: "/images/recipe3.jpg",
    prep: '10 mins',
    cook: '40 mins',
    difficulty: 'Easy',
    serves: '12',
    blurb: 'Bake these caramel pear blondies for an indulgent teatime treat. With a biscuity flavour that comes from browning the butter, they\'re moreish and chewy',
    ingredients: ['250g unsalted butter', '3 large eggs', '275g light brown soft sugar', '25g dark brown muscovado sugar', '1 tsp vanilla bean paste', '1 tsp fine sea salt', '200g plain flour', '1 tsp baking powder',  '100g dried pears', '100g dark chocolate', '3 tbsp caramel' ],
    method: ['Heat the oven to 180C/160C fan/gas 4. Butter and line a 20 x 20cm square cake tin.', 'Melt the butter in a saucepan over a medium heat, swirling it around. Allow to bubble for a few minutes, or until it turns a light golden brown and smells biscuity. Remove from the heat and leave to cool a little.', 'Tip the eggs into a large mixing bowl and whisk together with the light and dark sugars until just combined. Whisk through the melted butter, vanilla and salt.', 'Gently fold through the flour, baking powder, dried pears and most of the chocolate chunks, being careful not to overmix (this will make the blondies dense).', 'Pour the mixture into the lined tin. Top with the remaining chocolate and dollops of the caramel. Put in the centre of the oven to bake for 40 mins, or until a skewer inserted comes out with sticky crumbs (it shouldn’t be wet). Leave to cool completely in the tin. It will sink a little – the centre should be slightly squidgy. Cut into 12 squares. Will keep in an airtight container for up to three days.']
  },
  {
    id: 4,
    name: 'Fig sponge pudding',
    imageOne: "/images/recipe4.jpg",
    prep: '20 mins',
    cook: '1 hour',
    difficulty: 'Easy',
    serves: '6-8',
    blurb: 'Sponge pudding gets taken up a level with the addition of delicious baked figs and thyme, resulting in a seriously comforting wintry dessert. Serve warm with cream, ice cream or Greek yogurt',
    ingredients: ['250g butter', '5 tbsp golden syrup', '4 tbsp honey', '8 fresh figs', '4 large eggs', '250g golden caster sugar', '250g self-raising flour', '1 tsp baking powder',  '1 tsp vanilla extract' ],
    method: ['Heat the oven to 180C/160C fan/gas 4. Butter a 20 x 22cm ovenproof dish, then pour in the golden syrup and honey. Trim the stalks from the figs, then cut a deep cross in the top, just so they open out a bit, but be careful not to cut all the way through. Sit the figs upright on top of the syrup and put them in the oven to bake for 15-20 mins until softened and starting to caramelise a little at the edges.', 'While the figs are cooking, make the sponge mixture. Put the eggs, sugar, flour, baking powder, vanilla and butter in a bowl and use an electric whisk to beat until smooth. ', 'Remove the dish from the oven, scoop the figs out with a slotted spoon and set aside. Once the syrup mixture has cooled in the dish, take spoonfuls of the sponge batter and gently place them on top of the syrup. It’s best to do this all the way around the edge first, then end in the middle – this helps keep the syrup mixture separate. Smooth the batter out very gently to cover any gaps and seal the syrup mixture in.', 'Bake for 35-40 mins or until the sponge springs back when pressed. Allow to cool for around 5 mins or until just warm, then seconds before serving, dot the surface with eight small dollops of the yogurt. Top each mound with a baked fig, then scatter over some thyme leaves and drizzle with extra virgin olive oil, if you like.']
  },
  {
    id: 5,
    name: 'Pear & hazelnut clafoutis',
    imageOne: "/images/recipe5.jpg",
    prep: '10 mins',
    cook: '35 mins',
    difficulty: 'Easy',
    serves: '8',
    blurb: 'Combine the flavours of pear and hazelnut to make this stunning dessert. Make sure to serve the clafoutis warm – and don\'t forget the cream or crème fraîche',
    ingredients: ['45g blanched hazelnuts', '30g plain flour', '4 medium eggs', '150g caster sugar', '200ml milk', '300ml double cream', '2 tsp vanilla extract', '2-3 perfectly ripe pears' ],
    method: ['Heat oven to 180C/160C fan/gas 4. Put the hazelnuts in a food processor and whizz until finely ground. Add the flour, eggs, extra yolks, sugar, milk, cream and vanilla and whizz until you have a smooth batter.', 'Halve, core and slice the pears (you can peel them first if you like, but I usually don’t). Arrange the pear slices in a 26 x 33cm ceramic, cast iron or copper gratin dish, then pour in the batter. Bake for 30-35 mins, or until the batter is set in the centre, golden and slightly souffléd.', 'For the topping, toast the hazelnuts in a dry frying pan (keep a close eye on them – they can go from toasted to burnt very quickly), then roughly chop them so you’re left with a mixture of halved and more finely chopped nuts. Scatter over the clafoutis, then sieve a little icing sugar over the top. Leave to sit for 10-15 mins (the clafoutis will deflate a little). Serve warm with crème fraîche or pouring cream.']
  },
  {
    id: 6,
    name: 'Sticky ginger skillet parkin',
    imageOne: "/images/recipe6.jpg",
    prep: '10 mins',
    cook: '50 mins',
    difficulty: 'Easy',
    serves: '10-12',
    blurb: 'Try this one-pan pud/cake hybrid as an easy dessert for Bonfire Night, Halloween or cooler nights. Served straight from the oven, it’s perfect with custard',
    ingredients: ['200g salted butter', '85g light brown soft sugar', '85g treacle', '185g golden syrup', '250g self-raising flour', '2 tsp ground ginger', '1 tsp mixed spice', '100g porridge oats',  '2 large eggs', '2 tbsp milk', '2 balls stem ginger from a jar' ],
    method: ['Heat the oven to 150C/130C fan/gas 2. Put a heavy-bottomed 25cm ovenproof frying pan or skillet over a low heat and gently melt the butter, sugar, treacle and golden syrup together, stirring with a wooden spoon, until the butter is just melted and everything is combined. Remove from the heat and leave to cool slightly for 5-10 mins.', 'Sieve the flour and spices together, then mix in the oats. Whisk the eggs, milk, stem ginger and ginger syrup together in a bowl or jug. Stir the dry ingredients into the cooled butter mixture until well combined. Stir in the ginger, milk and egg mixture until you have a thick cake batter. Transfer to the oven and bake for 45-50 mins until firm and risen. Serve scooped from the pan with extra ginger syrup and custard or ice cream, if you like, or leave to cool and eat cold. Will keep, wrapped in baking parchment, for up to seven days. ']
  },
  {
    id: 7,
    name: 'Chicken, leek & mushroom pies',
    imageOne: "/images/recipe7.jpg",
    prep: '25 mins',
    cook: '55 mins',
    difficulty: 'Medium',
    serves: '6',
    blurb: 'Make these creamy chicken, leek and mushroom pies from scratch or use up leftover roast chicken and make a stock from the bones. They require a little extra effort, but they\'re worth ith',
    ingredients: ['50g butter', '3 leeks', '1 thyme sprig', '100g button mushrooms', '20g dried porcini mushrooms', '6 skinless and boneless chicken thighs', '30g flour', 'splash of white wine (optional)',  '300ml chicken stock', '100ml double cream', '½ lemon', '1 quantity pie pastry' ],
    method: ['Heat the butter in a shallow pan and gently cook the leeks with the thyme for 8 mins, or until soft. Add both types of mushrooms and cook for 5 mins more, then turn up the heat a little, add the chicken and stir until the chicken starts to brown. Scatter over the flour and stir to make a paste and continue to cook for 2 mins.', 'Splash in the wine, if using, and sizzle for 1 min, stirring, then pour in the stock, cream and lemon juice, season and simmer for 10 mins until the chicken is cooked through. Leave to cool, then pop in the fridge to chill. Can be made up to two days ahead. Assemble the pies as directed in Tom\'s pie pastry recipe, decorating the tops with any trimmings, if you like.']
  },
  {
    id: 8,
    name: 'Smoky spiced veggie rice',
    imageOne: "/images/recipe8.jpg",
    prep: '15 mins',
    cook: '1 hour',
    difficulty: 'Easy',
    serves: '6',
    blurb: 'Try this vegan take on a jambalaya, full of fiery and smoky flavours and bursting with vegetables. It\'s healthy, low in fat and calories, yet big on flavour ',
    ingredients: ['25g cashews', '4 tbsp olive oil', '1 corn cob', '250g rainbow baby carrots ', '2 red onions', '2 celery sticks ', '2 large red peppers', '3 garlic cloves',  '2 tbsp Cajun seasoning', '1½ tbsp smoked paprika', '1 tsp chipotle paste', '2 tbsp tomato purée', '200g heirloom cherry tomatoes', '400g can kidney beans', '400g can cherry tomatoes', '300g long-grain rice', '400ml vegetable stock', '1 tbsp red wine vinegar', '2 tbsp caster sugar', '2 spring onions' ],
    method: ['Dry-fry the cashews in a large saucepan or casserole dish over a medium heat until golden brown. Remove from the heat, leave to cool, then roughly chop. Heat 1 tbsp oil in the same pan over a high heat, then fry the corn on each side for 20 seconds to char. Remove from the pan, set aside, then tip in the carrots and fry for 5 mins. Remove from the pan and set aside.', 'Heat the rest of the oil in the same pan over a medium heat and fry the onions and celery for 10 mins until soft and slightly coloured. Tip in the peppers and garlic, then fry for another 5 mins before adding the Cajun seasoning, smoked paprika, chipotle paste and tomato purée. Fry for 1 min until the spices are fragrant, then add the cherry tomatoes and fry for another 2 mins. ', 'Stir in the kidney beans, canned tomatoes, rice, stock, vinegar and sugar, then stir until everything is combined. Bring to the boil, then cover with a lid and simmer with a lid on for 35-40 mins on a medium-low heat, stirring halfway through, until the rice is cooked and liquid absorbed.', 'Slice the corn off the cob and mix it through the rice along with the carrots. Season and garnish with the spring onions and cashews.']
  },
  {
    id: 9,
    name: 'Next level steak & ale pie',
    imageOne: "/images/recipe9.jpg",
    prep: '1 hour',
    cook: '3 hours',
    difficulty: 'Hard',
    serves: '6-8',
    blurb: 'Discover the secret ingredients that take the humble steak and ale pie to new levels. But, be warned: one slice just won\'t be enough',
    ingredients: ['1 tbsp vegetable oil', '100g smoked bacon', '1kg beef shin', '2 onions', '3 carrots', '3 tbsp plain flour', '1 tbsp tomato purée', '1 tbsp tomato purée',  '1 tsp malt or red wine vinegar', '1 tsp brown miso paste', '400ml sweet brown ale', '600ml beef stock made from 2 stock cubes', 'few thyme sprigs', '2 bay leaves' ],
    method: ['Heat the oven to 160C/140C fan/gas 3. Heat the vegetable oil in a large casserole dish and gently fry the bacon for 5 mins until lightly browned. Remove with a slotted spoon and set aside. In the same pan, brown the beef well in batches for 5-8 mins, adding a drizzle more oil if you need to, then set aside.', 'Add the onions and carrots to the pan and cook on a low heat for 5 mins. Stir in the flour, then add the tomato purée, vinegar and miso, if using. Tip the beef and bacon, along with any juices, back into the pan and give it all a good stir. Pour in the ale and stock, and nestle in the thyme stalks and bay. Season generously and bring to a simmer. Cover with a lid and cook in the oven for about 2 hrs or until the meat is really tender. Leave everything to cool slightly, then strain off about half the braising liquid into another container. Leave to cool completely. Can be made up to two days ahead and kept chilled in the fridge – the pie will be better if the filling is fridge-cold when added. Can also be frozen for up to three months.', 'To make the pastry, mix the flour, mustard powder, lard and butter with a generous pinch of sea salt until completely combined, then gradually add up to 250ml ice-cold water to make a soft dough. This can be done in a food processor if you prefer. Knead the thyme leaves into the pastry, then cover and leave to rest in the fridge for at least 1 hr. Can be made up to two days ahead and kept chilled, or frozen for up to a month.', 'Heat the oven to 220C/200C fan/gas 7 and put a baking tray in the oven. Heavily butter a 26-28cm pie dish and dust well with flour. Cut off a third of the pastry and set aside. Roll out the remaining pastry to a thick round that will easily line the pie dish with an overhang, then line the tin. Tip in the beef mixture. You want the filling to be slightly higher than the rim of the dish. Brush the edges with egg yolk. Roll out the remaining pastry to a thick round, big enough to cover the pie, then lift onto the pie dish. Trim the edges, crimp together, then re-roll the trimmings and cut into decorative shapes, such as leaves. Brush the top with more yolk. Make a hole in the centre of the pie with a knife, and put it on the hot baking tray.', 'Bake for 20 mins, remove, brush again with yolk, scatter with sea salt and bake for 20-25 mins until golden. Leave to rest for 10 mins while you heat up the extra gravy.']
  },
  {
    id: 10,
    name: 'Stuffed pumpkin',
    imageOne: "/images/recipe10.jpg",
    prep: '15 mins',
    cook: '1 Hour',
    difficulty: 'Easy',
    serves: '4',
    blurb: 'Throwing a vegan dinner party in the autumn or winter months? Bake a pumpkin with a gorgeous stuffing of rice, fennel, apple, pomegranate seeds and pecans',
    ingredients: ['1 medium-sized pumpkin', '4 tbsp olive oil', '100g wild rice', '1 large fennel bulb', '1 Bramley apple', '1 lemon', '1 tbsp fennel seeds', '½ tsp chilli flakes',  '2 garlic cloves', '30g pecans', '1 large pack parsley', '3 tbsp tahini', 'pomegranate seeds' ],
    method: ['Heat oven to 200C/180C fan/gas 6. Cut the top off the pumpkin or squash and use a metal spoon to scoop out the seeds. Get rid of any pithy bits but keep the seeds for another time (see our pumpkin seed recipe ideas). Put the pumpkin on a baking tray, rub with 2 tbsp of the oil inside and out, and season well. Roast in the centre of the oven for 45 mins or until tender, with the ‘lid’ on the side.', 'Meanwhile, rinse the wild rice well and cook following pack instructions, then spread out on a baking tray to cool. Thinly slice the fennel bulb and apple, then squeeze over ½ the lemon juice to stop them discolouring.', 'Heat the remaining 2 tbsp oil in a frying pan. Fry the fennel seeds and chilli flakes, then, once the seeds begin to pop, stir in ½ the garlic and the fennel. Cook for 5 mins until softened, then mix through the apple, pecans and lemon zest. Remove from the heat. Add the mixture to the the cooked rice, then stir in the chopped parsley and taste for seasoning.', 'Pack the mixture into the cooked pumpkin and return to the oven for 10-15 mins until everything is piping hot. Meanwhile, whisk the remaining lemon juice with the tahini, the rest of the garlic and enough water to make a dressing. Serve the pumpkin in the middle of the table, topped with pomegranate seeds and the dressing.']
  },
];
